# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: allzeros
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - mtr1
    - m1
    - m2
    - m3
    - m4
    - m5
    - m6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - m1
      - m2
      - m3
      - m4
      - m5
      - m6
  - name: rotor_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - mtr1
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - m1
    - m2
    - m3
    - m4
    - m5
    - m6
  gains:
    m1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
rotor_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - mtr1
  gains:
    mtr1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1